### PR TITLE
Fix bug where contact detail panel does not update

### LINKED ISSUE #220: Bug: ContactDetails does not clear after delete command
To recreate:
1) Add new person: `add n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 t/friends t/owesMoney`
2) Delete them using their index:` delete <INDEX>`

The contactDetails will still display the deleted person

### LINKED ISSUE #225: Bug: ContactDetails panel does not get updated after notes of a person is edited.
To recreate:
View 1
editnotes 1 i/1 n/test

the contact details panel would not get updated (only if the current view is the same as the person you wish to update)

### LINKED ISSUE #228: Bug: ContactDetails does not update after delete notes command
To recreate:

Run the delete note command

### LINKED ISSUE #266: Bug: ContactDetails does not update after undo command

### PR DESCRIPTION
**Pull request by Nicholas-Cheng-De-Fei**
Closes #220, closes #225, closes #228, closes #266

The following commands will update the contact detail panel only if the person is on the contact details panel:
- `editNotes`
- `deleteNotes`
- `delete`
- `clear`
- `undo`

### CODE REVIEW

**Review by ITLimJiaWei — APPROVED** [review]
LGTM

File: src/main/java/bizbook/logic/commands/DeleteCommand.java [hunk 1]
```diff
@@ -47,10 +47,13 @@ public CommandResult execute(Model model) throws CommandException {
 
         Person personToDelete = lastShownList.get(targetIndex.getZeroBased());
         model.deletePerson(personToDelete);
-        model.getFocusedPerson().set(null);
+        Person focusedPerson = model.getFocusedPerson().get();
+        // Need to clear the person from the contact details panel if we are deleting them
+        if (focusedPerson != null && focusedPerson.equals(personToDelete)) {
```
Comment (KennethTeo2002) [inline src/main/java/bizbook/logic/commands/DeleteCommand.java:52]:
```suggestion
        if (personToDelete.equals(focusedPerson)) {
```
Since person class has a null check in its equals function, this check can be simplified.

File: src/main/java/bizbook/ui/ContactDetails.java [hunk 2]
```diff
@@ -62,9 +62,14 @@ private void addNote(String note) {
      * @param person The person object to be updated onto the panel.
     */
     private void displayPerson(Person person) {
-        logger.info("Displaying info of " + person.toString());
         clearPanel();
 
+        if (person == null) {
```
Comment (KennethTeo2002) [inline src/main/java/bizbook/ui/ContactDetails.java:67]: Could this be done using the equals method instead?

**Review by KennethTeo2002 — CHANGES_REQUESTED** [review]

**Review by KennethTeo2002 — CHANGES_REQUESTED** [review]
The edit command should also update the panel

**Review by KennethTeo2002 — APPROVED** [review]
LGTM
