### PR TITLE
Bug fixes for Phone & Unit Test for Edit Notes Parser

### LINKED ISSUE #269: Bug: GUI gets pushed downwards after adding a lot of notes for a person
image

This will not be an issue if the window is small but if we were to add more than 10 notes in full screen the input box will not be visible and resizing the window will not help

### PR DESCRIPTION
**Pull request by sheenkerr**
Closes #269 & #268

Changed Regex for phone to be exactly 8 digits starting with 6, 8 or 9.

Add success test case to Edit Notes Parser Command

### CODE REVIEW

File: src/main/java/bizbook/logic/commands/EditNotesCommand.java [hunk 1]
```diff
@@ -94,9 +94,24 @@ private Person updateNote(Person personToEdit, ArrayList<Note> notesToEdit) {
...
     }
 
+    @Override
+    public boolean equals(Object other) {
+        if (other == this) {
+            return true;
+        }
+
+        // instanceof handles nulls
+        if (!(other instanceof EditNotesCommand otherEditNotesCommand)) {
```
Comment (joeltio) [inline src/main/java/bizbook/logic/commands/EditNotesCommand.java:108]: I like this new syntax!

**Review by joeltio — APPROVED** [review]
LGTM, please seprate EditNotes to another PR in the future yeah.

EditNotes itself is missing tests for equals and toString.

**Review by ITLimJiaWei — APPROVED** [review]
LGTM
